#!/bin/bash -e

if [ $# -ne 1 ]; then
    echo "Usage: ./hack/run [build,update]"
    exit
fi

if [ "$TYPE" == "component" ]; then
  REPO=${REPO:-"$NAME-$TYPE"}
else
  REPO=${REPO:-"$TYPE-$NAME"}
fi

if [ "$1" == "build" ]; then
  source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/build
fi

if [ "$1" == "update" ]; then
  source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/update
fi
